"use strict";

const { execFileSync } = require("node:child_process");
const { basename } = require("node:path");

const DATA = require("./linguist.json");

const byExtension = new Map();
const byFilename = new Map();
const byInterpreter = new Map();
for (const [name, one] of Object.entries(DATA.languages)) {
  const add = (held, key) => {
    if (!held.has(key)) held.set(key, []);
    held.get(key).push(name);
  };
  for (const ext of one.extensions ?? []) add(byExtension, ext.toLowerCase());
  for (const file of one.filenames ?? []) add(byFilename, file);
  for (const run of one.interpreters ?? []) add(byInterpreter, run);
}
const DOCUMENTATION = DATA.documentation.map((one) => new RegExp(one, "m"));
const VENDORED = DATA.vendored.map((one) => new RegExp(one, "m"));
const RULES = new Map();
for (const one of DATA.disambiguations) for (const ext of one.extensions) RULES.set(ext.toLowerCase(), one.rules);

const GENERATED_NAME = /(^|\/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|composer\.lock|Gemfile\.lock|poetry\.lock|go\.sum)$|\.map$|_pb2\.py$|\.pb\.(go|cc|h)$|\.designer\.(cs|vb)$/;
const GENERATED_MARK = /generated by|do not edit|@generated|auto-?generated/i;

function candidatesOf(path, head) {
  const name = basename(path);
  if (byFilename.has(name)) return byFilename.get(name);
  for (let at = name.indexOf("."); at >= 0; at = name.indexOf(".", at + 1)) {
    const ext = name.slice(at).toLowerCase();
    if (byExtension.has(ext)) return byExtension.get(ext);
  }
  const bang = head.match(/^#!\s*(\S+)(?:\s+(.*))?/);
  if (bang) {
    let run = basename(bang[1]);
    if (run === "env") run = (bang[2] ?? "").split(/\s+/).find((one) => one && !one.startsWith("-") && !one.includes("=")) ?? "";
    run = basename(run);
    return byInterpreter.get(run) ?? byInterpreter.get(run.replace(/[\d.]+$/, "")) ?? [];
  }
  return [];
}

function holds(rule, text) {
  if (rule.pattern === null) return false;
  if (rule.pattern && !new RegExp(rule.pattern, "m").test(text)) return false;
  if (rule.negative && new RegExp(rule.negative, "m").test(text)) return false;
  return (rule.and ?? []).every((one) => holds(one, text));
}

function languageOf(path, head, forced) {
  if (forced) {
    const named = Object.keys(DATA.languages).find((one) => one.toLowerCase() === forced.toLowerCase().replace(/-/g, " "));
    if (named) return { name: DATA.languages[named].group ?? named, type: DATA.languages[named].type };
  }
  let found = candidatesOf(path, head);
  if (found.length > 1) {
    const name = basename(path);
    const ext = [...RULES.keys()].filter((one) => name.toLowerCase().endsWith(one)).sort((a, b) => b.length - a.length)[0];
    for (const rule of RULES.get(ext) ?? []) {
      if (!holds(rule, head)) continue;
      const narrowed = found.filter((one) => (rule.language ?? []).includes(one));
      if (narrowed.length > 0) found = narrowed;
      break;
    }
  }
  if (found.length === 0) return null;
  const pick = found.find((one) => DATA.languages[one].type === "programming") ?? found[0];
  return { name: DATA.languages[pick].group ?? pick, type: DATA.languages[pick].type };
}

function generated(path, head) {
  if (GENERATED_NAME.test(path)) return true;
  if (GENERATED_MARK.test(head.split("\n").slice(0, 5).join("\n"))) return true;
  if (/\.(js|css)$/i.test(path)) {
    const lines = head.split("\n");
    if (lines.length > 0 && head.length / lines.length > 110) return true;
  }
  return false;
}

function attributesOf(root, paths) {
  const held = new Map();
  if (paths.length === 0) return held;
  let out = "";
  try {
    out = execFileSync("git", ["check-attr", "-z", "--stdin", "linguist-vendored", "linguist-generated",
      "linguist-documentation", "linguist-language", "linguist-detectable"], {
      cwd: root, input: paths.join("\0"), encoding: "utf8", maxBuffer: 256 * 1024 * 1024, stdio: ["pipe", "pipe", "ignore"],
    });
  } catch {
    return held;
  }
  const parts = out.split("\0");
  for (let at = 0; at + 2 < parts.length; at += 3) {
    const [path, attribute, value] = parts.slice(at, at + 3);
    if (value === "unspecified") continue;
    if (!held.has(path)) held.set(path, {});
    held.get(path)[attribute.replace("linguist-", "")] = value === "set" || value === "true" ? true : value === "unset" || value === "false" ? false : value;
  }
  return held;
}

function counted(path, head, attributes = {}) {
  const language = languageOf(path, head, typeof attributes.language === "string" ? attributes.language : null);
  if (!language) return null;
  const pick = (said, found) => (said === undefined ? found : said === true);
  if (pick(attributes.vendored, VENDORED.some((one) => one.test(path)))) return null;
  if (pick(attributes.generated, generated(path, head))) return null;
  if (pick(attributes.documentation, DOCUMENTATION.some((one) => one.test(path)))) return null;
  const detectable = attributes.detectable === undefined ? ["programming", "markup"].includes(language.type) : attributes.detectable === true;
  return detectable ? language.name : null;
}

module.exports = { attributesOf, counted, languageOf };
